In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import string as string

In [ ]:
A2022 = '/content/drive/MyDrive/Copy of A2022_dataset_buat bedah data.csv'
kode = '/content/drive/MyDrive/kode_provkabkot.csv'
prov_code = '/content/drive/MyDrive/fix_prov_code.csv'

In [ ]:
df_A2022 = pd.read_csv(A2022, sep=';')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (7,14,15,17,19,21,22,23,25,27,28,30,32,34,36,37,39,41,43,45,47,49,50,54,56,57,59) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
df_prov_code = pd.read_csv(prov_code,sep=';')

In [ ]:
df=df_A2022.copy()

In [ ]:
col_num = [11,12,13,14,31]

In [ ]:
a = {}
for i in col_num:
  a[df.columns[i]]=df.iloc[:,i].unique()


a.keys()

dict_keys(['kodefungsi', 'namafungsi', 'kodesubfungsi', 'namasubfungsi', 'namasubkegiatan'])

In [ ]:
# temp=[]
# for x in a['namafungsi']:
#   try:
#     temp.append(x.lower())
#   except:
#     temp.append('null')
# a['namafungsi']=temp

In [ ]:
df['kodeprovinsi']=df.loc[:,'kodepemda'].apply(lambda x: str(x).split('.')[0])
df['kodekabkot'] = df.loc[:,'kodepemda'].apply(lambda x: str(x).split('.')[1])

In [ ]:
df['kodeprovinsi'].nunique()

34

In [ ]:
df['kodekabkot'].nunique()

39

In [ ]:
a = []
for i in col_num:
  for i_row,words in enumerate(df.iloc[:,i]):
    try:
      words.lower()
    except:
      continue
    if('sanitasi' in words.lower()):
      # print(words)
      a.append((i_row,df.columns[i],words,df.loc[i_row,'kodeprovinsi']))

len(a)

1065

In [ ]:
df_a = pd.DataFrame(a, columns = ['i_row', 'col_name','col_value','prov'])

In [ ]:
i = list(df_a['i_row'])

In [ ]:
df['tahun'].unique()

array([2022])

In [ ]:
df['bulan'].unique()

array([ 0., nan])

In [ ]:
group = ['tahun','bulan','namasubkegiatan','namaprogram','namaoutcome','kodeprovinsi','kodekabkot']


In [ ]:
df['kodeprovinsi']=pd.to_numeric(df['kodeprovinsi'])

In [ ]:
df['kodeprovinsi'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [ ]:
df_sanitasi = df.iloc[i,:].groupby(group, as_index=False).sum()

In [ ]:
# df_sanitasi.to_csv('df_sanitasi_1.csv')

In [ ]:
df_kod = pd.read_csv(kode,sep=';', encoding =  "ISO-8859-1")

In [ ]:
df_kod['NAMA_PROVINSI'].nunique()

32

In [ ]:
df_kod.columns

Index(['NAMA_PROVINSI', 'KODE_PROVINSI'], dtype='object')

In [ ]:
# res = df_sanitasi.merge(df_kod, how='inner', left_on=['kodeprovinsi'], right_on=['KODE_PROVINSI'])

In [ ]:
# res = res.drop(['KODE_KABKOT','NAMA_KABKOT'],axis=1)

In [ ]:
# res.to_csv('result.csv')

In [ ]:
# from google.colab import files
# res.to_csv('result.csv') 
# files.download('result.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5242575 entries, 0 to 5242574
Data columns (total 62 columns):
 #   Column                  Dtype  
---  ------                  -----  
 0   kodepemda               float64
 1   namapemda               object 
 2   sumber                  object 
 3   tahun                   int64  
 4   bulan                   float64
 5   kodedata                int64  
 6   jeniscoa                float64
 7   nomorperda              object 
 8   tanggalperda            object 
 9   namaaplikasi            object 
 10  pengembangaplikasi      object 
 11  kodefungsi              float64
 12  namafungsi              object 
 13  kodesubfungsi           float64
 14  namasubfungsi           object 
 15  kodeurusanprogram       object 
 16  namaurusanprogram       object 
 17  kodeurusanpelaksana     object 
 18  namaurusanpelaksana     object 
 19  kodeskpd                object 
 20  namaskpd                object 
 21  kodeunitskpd            object 

In [ ]:
a = df['namasubkegiatan'].astype(str)
a = pd.DataFrame(a, columns = ['namasubkegiatan'])

In [ ]:
def if_sanitasi(x):
  if('sanitasi' in str(x).lower()):
    return 1
  else:
    return 0


In [ ]:
col = ['tahun', 'bulan', 'namasubkegiatan','kodeprovinsi','nilaianggaran']
at = df[col]
at['flag_sanitasi'] = at.loc[:,'namasubkegiatan'].apply (lambda row: if_sanitasi(row))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
grouped = at.groupby(['tahun','bulan','kodeprovinsi','flag_sanitasi'],as_index = False)['nilaianggaran'].sum()

In [ ]:
df_prov_code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   NAMA_PROVINSI  45 non-null     object
 1   KODE_PROVINSI  45 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 848.0+ bytes


In [ ]:
grouped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   tahun          67 non-null     int64  
 1   bulan          67 non-null     float64
 2   kodeprovinsi   67 non-null     int64  
 3   flag_sanitasi  67 non-null     int64  
 4   nilaianggaran  67 non-null     float64
dtypes: float64(2), int64(3)
memory usage: 2.7 KB


In [ ]:
result = grouped.merge(df_prov_code, how='inner', left_on=['kodeprovinsi'], right_on=['KODE_PROVINSI'])

In [ ]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 65 entries, 0 to 64
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   tahun          65 non-null     int64  
 1   bulan          65 non-null     float64
 2   kodeprovinsi   65 non-null     int64  
 3   flag_sanitasi  65 non-null     int64  
 4   nilaianggaran  65 non-null     float64
 5   NAMA_PROVINSI  65 non-null     object 
 6   KODE_PROVINSI  65 non-null     int64  
dtypes: float64(2), int64(4), object(1)
memory usage: 6.1+ KB


In [ ]:
result = result.drop(['kodeprovinsi'],axis = 1)

In [ ]:
from google.colab import files
result.to_csv('result.csv') 
files.download('result.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# def if_sanitasi(row):
#   try:

#    if str in strrrr:
#            return 1
#     else: return 0

# df['flag_sanitasi'] = df.apply (lambda row: if_sanitasi(row), axis=1)

In [ ]:
result

tahun  bulan  flag_sanitasi  nilaianggaran   NAMA_PROVINSI  KODE_PROVINSI
0    2022    0.0              0   9.080029e+13     DKI JAKARTA              1
1    2022    0.0              1   2.255884e+08     DKI JAKARTA              1
2    2022    0.0              0   1.185947e+14      JAWA BARAT              2
3    2022    0.0              1   8.535202e+08      JAWA BARAT              2
4    2022    0.0              0   5.221052e+13     JAWA TENGAH              3
..    ...    ...            ...            ...             ...            ...
60   2022    0.0              1   1.754998e+09  KEPULAUAN RIAU             32
61   2022    0.0              0   1.619196e+13     PAPUA BARAT             33
62   2022    0.0              1   8.900000e+07     PAPUA BARAT             33
63   2022    0.0              0   1.616243e+13  SULAWESI BARAT             34
64   2022    0.0              1   9.740000e+07  SULAWESI BARAT             34

[65 rows x 6 columns]